#SPDX-License-Identifier: MIT-0
---
# vars file for FrontendServer
# Set remote_user conditionally for each server role
    ansible_user: "{{ 'rocky' if 'server_role_redis_server' in group_names else 'ubuntu' }}"
