- name: Roles for the Redis servers
  hosts: server_role_redis_server
  become: true
#  vars:
 #   ansible_user: rocky
  roles:
    - Redis

- name: Roles for the Frontend servers
  hosts: server_role_frontend_server
  become: true
#  vars:
 #   ansible_user: ubuntu
  roles:
    - FrontendServer
